server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL문 정렬하여 출력

upload:
  path: 'C:/fileUpload'

#로깅 설정
logging:
  config: classpath:logback-spring-local.xml